import { build } from 'esbuild';
import { mkdir,rm,writeFile,cp,readFile } from 'node:fs/promises';
const options={bundle:true,format:'esm',target:'es2022',logLevel:'warning'};
await mkdir('build',{recursive:true});
await build({...options,platform:'node',entryPoints:['src/engine.ts','src/url.ts','src/catalog.ts','src/expectations.ts','src/report.ts','src/capture.ts','src/acquisition.ts','src/examples.ts','src/cli.ts'],outdir:'build',outExtension:{'.js':'.mjs'}});
await import('./fixtures.mjs?'+Date.now());
try {await readFile('src/render.ts','utf8');}catch{process.exit(0);}
await build({...options,platform:'node',entryPoints:['src/render.ts'],outdir:'build',outExtension:{'.js':'.mjs'}});
const {renderSite,renderMethod,renderCatalog}=await import('../build/render.mjs?'+Date.now());
const worker=await build({...options,platform:'browser',entryPoints:['src/worker.ts'],write:false,minify:true});
await writeFile('src/worker.generated.ts','// Generated by build. No network acquisition code.\nexport default '+JSON.stringify(worker.outputFiles[0].text)+';\n');
await rm('dist',{recursive:true,force:true});await mkdir('dist/assets',{recursive:true});
await build({...options,platform:'browser',entryPoints:['src/app.ts'],outfile:'dist/assets/app.js',minify:true,metafile:true}).then(r=>writeFile('build/browser-metafile.json',JSON.stringify(r.metafile,null,2)));
await cp('public','dist',{recursive:true});
const oracle=await readFile('proofs/oracle.json','utf8').then(JSON.parse).catch(()=>undefined);
await writeFile('dist/index.html',await renderSite(oracle));await writeFile('dist/methode.html',renderMethod());await writeFile('dist/catalogue.html',await renderCatalog());
await cp('examples','dist/examples',{recursive:true});await cp('schemas','dist/schemas',{recursive:true});
await writeFile('dist/.nojekyll','');
console.log('Built static site + shared Node modules.');
