import {writeFile} from 'node:fs/promises';
const str={type:'string'},hash={type:'string',pattern:'^[a-f0-9]{64}$'},bool={type:'boolean'},integer={type:'integer',minimum:0};
const obj=(properties,required=Object.keys(properties),additionalProperties=false)=>({type:'object',properties,required,additionalProperties});
const arr=items=>({type:'array',items});
const decision={enum:['allow','disallow','indeterminate','out_of_scope']},status={enum:['pass','fail','inconclusive','invalid']};
const caseSchema=obj({id:{type:'string',minLength:1},profile:{type:'string',minLength:1},dimension:{enum:['crawl','usage']},url:{type:'string',minLength:1},expected:{enum:['allow','disallow']},reason:str,genericToken:{type:'string',pattern:'^[a-zA-Z_-]+$'}},['id','profile','dimension','url','expected','reason'],true);
const expectations=obj({schemaVersion:{const:1},origin:{type:'string',pattern:'^https?://'},cases:{...arr(caseSchema),minItems:1,maxItems:5000}});
const capture=obj({schemaVersion:{const:1},synthetic:bool,capturedAt:str,tool:str,origin:str,requestedURL:str,redirects:{...arr(obj({url:str,status:{type:'integer'},location:str})),maxItems:5},finalURL:str,status:{type:['integer','null']},requestCount:{type:'integer',minimum:0,maximum:6},userAgent:str,headers:{type:'object',additionalProperties:str},bodyBase64:str,bytes:{type:'integer',minimum:0,maximum:2097152},sha256:hash,complete:bool,truncated:bool,encoding:{const:'utf-8'},diagnostics:arr(str)});
const rule=obj({kind:{enum:['allow','disallow']},value:str,pattern:str,line:{type:'integer',minimum:1},raw:str},undefined,true);
const model=obj({decision:{enum:['allow','disallow','indeterminate']},groups:arr(obj({id:{type:'integer'},agents:arr(obj({token:str,value:str,line:{type:'integer'}})),rules:arr(rule)})),matched:arr({...rule,required:[...rule.required,'priority','effectivePattern'],properties:{...rule.properties,priority:integer,effectivePattern:str}}),decisive:arr({...rule,required:[...rule.required,'priority','effectivePattern'],properties:{...rule.properties,priority:integer,effectivePattern:str}}),reason:str});
const result=obj({case:{},row:{type:'integer',minimum:1},prepared:{type:'object'},resolution:{type:'object'},model,decision,status,code:str,explanation:str},['case','row','decision','status','code','explanation']);
const file=obj({sha256:hash,bytes:integer,diagnostics:arr(obj({line:{type:'integer'},level:{enum:['info','warning','error']},message:str},['level','message'])),results:arr(result),summary:obj({pass:integer,fail:integer,inconclusive:integer,invalid:integer,evaluated:integer,uncertain:integer}),exitCode:{enum:[0,1,2]}});
// Reports preserve invalid cases too. Expectations schema applies only to admissible inputs.
const report=obj({schemaVersion:{const:1},createdAt:str,tool:str,engine:str,reference:{type:'string',pattern:'^[a-f0-9]{40}$'},catalog:obj({version:str,sha256:hash}),manifest:obj({schemaVersion:{const:1},origin:str,cases:arr({})}),issues:arr(obj({row:{type:'integer'},field:str,message:str},['field','message'])),before:file,after:file,contentIdentical:bool,decisionChanges:integer,caseDecisionsIdentical:bool,exitCode:{enum:[0,1,2]},note:str,delivery:obj({capture,usable:bool,diagnostics:arr(str),ruleCalculation:str},['usable','diagnostics'])},['schemaVersion','createdAt','tool','engine','reference','catalog','manifest','issues','after','exitCode','note']);
for(const [name,schema] of Object.entries({expectations,report,capture}))await writeFile('schemas/'+name+'.schema.json',JSON.stringify({$schema:'http://json-schema.org/draft-07/schema#',title:'Edikka robots review '+name+' v1',...schema},null,2)+'\n');
