import type { Manifest, Case } from './expectations';
export const before='User-agent: *\nDisallow: /documents/\n';
export const proposed=before+'\nUser-agent: GPTBot\nDisallow: /blog/\n';
export const corrected=before+'\nUser-agent: GPTBot\nDisallow: /documents/\nDisallow: /blog/\n';
const c=(id:string,profile:string,url:string,expected:Case['expected'],reason:string,dimension:Case['dimension']='crawl'):Case=>({id,profile,dimension,url,expected,reason});
export const expectations:Manifest={schemaVersion:1,origin:'https://example.com',cases:[c('documents','GPTBot','/documents/guide.pdf','disallow','Conserver l’exclusion des documents.'),c('blog','GPTBot','/blog/article','disallow','Ajouter l’exclusion du blog pour GPTBot.'),c('search-blog','OAI-SearchBot','/blog/article','allow','Conserver la possibilité de recherche OpenAI.'),c('search-docs','OAI-SearchBot','/documents/guide.pdf','disallow','Conserver les documents hors exploration déclarée.'),c('public','GPTBot','/a-propos','allow','Laisser la page publique autorisée.') ]};
export type Example={id:string;title:string;intro:string;before:string;after:string;manifest:Manifest;syntheticDelivery?:boolean};
const manifest=(cases:Case[]):Manifest=>({schemaVersion:1,origin:'https://example.com',cases});
export const EXAMPLES:Example[]=[
 {id:'main',title:'Un groupe spécifique ouvre les documents',intro:'L’ajout d’un groupe GPTBot remplace le groupe général pour ce profil. Ses restrictions ne sont pas héritées.',before,after:proposed,manifest:expectations},
 {id:'exception',title:'A · Une exception plus précise',intro:'Allow /documents/public/ prévaut sur Disallow /documents/. L’ordre des lignes ne décide pas du résultat.',before:'User-agent: *\nDisallow: /documents/\n',after:'User-agent: *\nAllow: /documents/public/\nDisallow: /documents/\n',manifest:manifest([c('public','GPTBot','/documents/public/guide.pdf','allow','Autoriser le sous-répertoire public.'),c('private','GPTBot','/documents/private.pdf','disallow','Maintenir l’exclusion du reste.')])},
 {id:'fallback',title:'B · Le repli Googlebot-Image',intro:'Le résolveur choisit Googlebot en l’absence de Googlebot-Image. Dès qu’un groupe spécifique apparaît, il le choisit seul.',before:'User-agent: Googlebot\nDisallow: /images/\n',after:'User-agent: Googlebot\nDisallow: /images/\n\nUser-agent: Googlebot-Image\nAllow: /images/\n',manifest:manifest([c('image','Googlebot-Image','/images/photo.jpg','allow','Autoriser l’exploration Images avec un groupe dédié.')])},
 {id:'usage',title:'C · Usage et exploration sont distincts',intro:'Google-Extended modifie un contrôle d’usage, sans modifier la règle d’exploration Googlebot. Ce n’est pas un deuxième robot HTTP.',before:'User-agent: Googlebot\nAllow: /\n',after:'User-agent: Googlebot\nAllow: /\n\nUser-agent: Google-Extended\nDisallow: /\n',manifest:manifest([c('crawl','Googlebot','/article','allow','Maintenir l’exploration Search.'),c('usage','Google-Extended','/article','disallow','Refuser les usages Gemini couverts par ce jeton.','usage')])},
 {id:'preproduction',title:'D · Le fichier de préproduction a été servi',intro:'Capture synthétique : le fichier reçu interdit tout, alors que les attentes autorisent les pages publiques. Aucune requête réelle n’a été effectuée.',before:'User-agent: *\nAllow: /\n',after:'User-agent: *\nDisallow: /\n',syntheticDelivery:true,manifest:manifest([c('home','Googlebot','/','allow','Page publique.'),c('article','OAI-SearchBot','/article','allow','Article public.')])},
 {id:'delivery',title:'E · Le contenu diffère, la cause reste à chercher',intro:'Capture synthétique : un commentaire peut changer sans effet sur les cas. Une règle modifiée peut changer une décision. Aucun opérateur n’est désigné comme responsable.',before:corrected,after:'# Commentaire de livraison, sans effet sur les cas\n'+corrected,syntheticDelivery:true,manifest:expectations}
];
